### PR TITLE
Fixed a simple mistake

### PR DESCRIPTION
**Pull request by PocketKiller**

### CODE REVIEW

**Comment by jojoe77777** [comment]
I thought I had tried that and it didn't work for some reason. ah well.

**Comment by PocketKiller** [comment]
TRAVIS?!

**Comment by jojoe77777** [comment]
Do we have Travis? @legoboy0215

**Comment by PocketKiller** [comment]
it appears you do. Travis failed.

**Comment by legoboy0215** [comment]
I can add it :)

**Pull request merged**
