### PR TITLE
Legoboy0215

### PR DESCRIPTION
**Pull request by legoboy0215**

### CODE REVIEW

**Comment by jojoe77777** [comment]
ooh

**Comment by legoboy0215** [comment]
Nothing... Renaming. Check out the README BTW. Cool work :)

**Comment by jojoe77777** [comment]
Nice, I'm not good at markdown XD

**Comment by legoboy0215** [comment]
:)

**Comment by legoboy0215** [comment]
I hope we are always active, not like LegendsOfMCPE

**Pull request merged**
